### ISSUE TITLE
Save dialog bug

### ISSUE THREAD

**Issue by fjthrowaway** [ZaWertun/gtk3-nocsd#13]
Hi

I can't save files anymore while gtk3-nocsd is active. The field where you can type in the file name is missing.
Problem started with c7e153f85bdeb8dc8d60a951dbc6ce1448e2f84e. Older versions work fine and don't have this issue.
I'm using XFCE 4.16.3 (the latest version). How to reproduce: open mousepad, type something and try to save.

Thank you for your help

**Comment by ZaWertun** [comment]
Just tried to reproduce this bug on mousepad-0.5.5 - no luck.
Please specify versions of mousepad & gtk3.

Do you try gtk3-nocsd from master with commit c7e153f85bdeb8dc8d60a951dbc6ce1448e2f84e reverted?

**Comment by ZaWertun** [comment]
And please specify which distrubution are you using. Is it Arch?

**Comment by fjthrowaway** [comment]
Yes, I'm using Arch. I don't really know how to revert commits but here you can see the problem in action:


https://user-images.githubusercontent.com/78733821/122656713-7f218900-d15d-11eb-965e-8a7322d75465.mp4

gtk3 version: 3.24.29
mousepad version: 0.5.5

**Comment by fjthrowaway** [comment]
Found a workaround:

`xfconf-query -c xsettings -p /Gtk/DialogsUseHeader -s false`

[source](https://winaero.com/disable-client-side-decorations-in-xfce-for-open-save-dialog/)

**Comment by ZaWertun** [comment]
> Found a workaround:
> 
> `xfconf-query -c xsettings -p /Gtk/DialogsUseHeader -s false`
> 
> [source](https://winaero.com/disable-client-side-decorations-in-xfce-for-open-save-dialog/)

Nice finding! Now I can reproduce this bug on my side. Thanks!

**Comment by ZaWertun** [comment]
Should be fixed in cee7ed2a2d7fc9a0e081dafe721e42fad0dcb8da.
