### ISSUE TITLE
Hiding header label with CSS rules removes information from some GTK software

### ISSUE THREAD

**Issue by neoninteger** [ZaWertun/gtk3-nocsd#3]
Hi, sorry I've been busy with exams over the last few days.

> I can do this:
>
> 1. Disable header hiding by default;
> 2. Enable header hiding when env variable `GTK3NOCSD_HIDE_HEADER=1` was set.
>
> Or enable by default and disable by env variable - I do not know which is better.
> What do you think about this?

Putting this behind an environment variable is a very good idea.

There's likely more use cases that warrant having the header label hidden by default, so I think its fine to leave that as is, but providing the option to show that label would certainly be beneficial.

**Comment by ZaWertun** [comment]
Check this commit: aa76c16e24212b5fb6cfb9ea1d54dd81729f6bae.
Also some testing needed.

**Comment by neoninteger** [comment]
The stated commit works fine on my end, cheers!

**Comment by ZaWertun** [comment]
Ok, i'm closing the issue then.
