### ISSUE TITLE
3.0.2 strip Nautilus of its whole toolbar

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [ZaWertun/gtk3-nocsd#4]
Some of the changes made in July makes Nautilus to lose its toolbar completely, older version worked properly. I didn't notice any ill effects to other gtk3 apps, though.

GTK3 3.24.21-1
Nautilus 3.36.3-1
Arch Linux
gtk3-nocsd built from AUR

**Comment by ZaWertun** [comment]
Please check last commit (cea22bbcaabbab13954bdc763e14cc375a2b400e).
Thanks for feedback!

**Comment by cyberpunkrocker-zero** [comment]
So far, seems to be working again. Thanks!
