### ISSUE TITLE
Toolbar missing on save-dialog

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [ZaWertun/gtk3-nocsd#5]
Found another issue on latest version:
Cawbird (a twitter client): when right-clicking an image to save it, the save dialog is missing the toolbar, making it impossible to use. The old PCMan version works.

Cawbird 1.1.0-1
GTK3 3.24.21-1
Arch Linux

**Comment by ZaWertun** [comment]
Got it, I'll check this.
I've added code to hide empty GtkHeaderBar - this small change causing all this issues.

**Comment by ZaWertun** [comment]
Could you post screenshot of this issue?

There is how Cawbird save dialog looks like on my machine:
![image](https://user-images.githubusercontent.com/1080298/89274594-d43dd480-d649-11ea-9735-c5e978de07e9.png)

gtk3-nocsd built from master branch (commit cea22bbcaabbab13954bdc763e14cc375a2b400e) not affecting save dialog.

**Comment by cyberpunkrocker-zero** [comment]
On the left is r55.82ff5a0 (i.e. PCMan version), on the right is r71.cea22bb. As you can see, the whole top row is missing. Window manager is Awesome WM, no composite used.
![r55-r71](https://user-images.githubusercontent.com/122680/89323015-ca3dc500-d68d-11ea-93e9-7cf88ffdeca6.png)

**Comment by ZaWertun** [comment]
Please run cawbird with `GTK_DEBUG=interactive`:
`GTK_DEBUG=interactive cawbird` and select this toolbar with file name in the inspector
(looks like this: 
![изображение](https://user-images.githubusercontent.com/1080298/89325544-a11f3380-d691-11ea-82aa-400557a3bd3f.png)).
Then show me component tree:
![изображение](https://user-images.githubusercontent.com/1080298/89325687-d3309580-d691-11ea-8bdc-cf81a4fa304a.png)

GtkFileChooserDialog is not using GtkHeaderBar so - it can't be broken with last code. Are you sure that you use last code from the git?

Can't reproduce this on my computer.

**Comment by ZaWertun** [comment]
P.S. I have same versions of GTK3 and Cawbird: gtk3-3.24.21-1.fc32.x86_64, cawbird-1.1.0-2.fc32.x86_64.

**Comment by ZaWertun** [comment]
I'll try to reproduce this bug in the VM with ArchLinux.

**Comment by cyberpunkrocker-zero** [comment]
I wasn't sure which version I was supposed to be using while debugging, so this is from version 82ff5a0. As for whether I'm using the latest code, shouldn't 'makepkg -f' force fetching the latest from git? At least the resulting package has 'cea22bb' in the filename.
![cawbird-debug](https://user-images.githubusercontent.com/122680/89329754-e9d9eb00-d697-11ea-88a1-70870a664856.png)

**Comment by ZaWertun** [comment]
Work as intended when installed from git (git clone ... && make ...).
1. ![VirtualBox_ArchLinux_04_08_2020_23_05_59](https://user-images.githubusercontent.com/1080298/89339687-40025a80-d6a7-11ea-945b-641477dfc139.png)
2. ![VirtualBox_ArchLinux_04_08_2020_23_07_59](https://user-images.githubusercontent.com/1080298/89339778-61fbdd00-d6a7-11ea-8d06-d0b761280193.png)

How to install `gtk3-nocsd` from Aur?

**Comment by neon64** [comment]
Can confirm this issue on swaywm (wayland) & Arch Linux, but from doing a `git clone` and compiling myself (not using the AUR package).

The original PCMan version works fine, as does v3.0.1 from here. But both v3.0.2 and v3.0.3 are broken for me (first time I use the save dialog in Firefox the title/save button shows up, second time fails). So seems to be something between v3.0.1 and v3.02 broke things.

**Comment by ZaWertun** [comment]
Please describe all steps, especially how do you run the `cawbird` in the terminal.

If you run just `gtk3-nocsd cawbird` without supplying `LD_PRELOAD` variable - you still have been using `libgtk3-nocsd.so.0` installed from AUR.
I.E. you still using old version.

**Comment by ZaWertun** [comment]
Nah. Just removed this code.
Now everything should work as before, check tag `v3.0.4`.
Thanks for feedback btw.

**Comment by neon64** [comment]
I don't have a Twitter account, so haven't reproduced it with cawbird specifically, but instead with other apps with a GTK save dialog, such as Firefox and Evince.

This doesn't work:

    git checkout v3.0.2
    make
    env GTK_CSD=0 LD_PRELOAD=/home/[username]/code/gtk3-nocsd2/libgtk3-nocsd.so.0 evince

Can confirm v3.0.4 has fixed it for me!

Thanks for your work on this - gnome apps without csd now fit in really well in my tiling wm setup :)
